#%RAML 1.0
---

title: Get State Pension calculation
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

/individuals/state-pension-calculation:

  /calculation:
    post:
      displayName: Get a State Pension calculation
      description: Gets a State Pension calculation for an individual.
      is: [headers.acceptHeader]
      (annotations.scope): "read:state-pension-calculation"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:state-pension-calculation" ] } ]

      body:
        application/json:
          type: !include docs/schemas/get-calculation/request.json
          examples:
            example-1:
              description: Get initial calculation
              value: !include docs/examples/get-calculation/request-initial.json
            example-2:
              description: Get final calculation using a FRY amount.
              value: !include docs/examples/get-calculation/request-final-with-fry.json
            example-3:
              description: Get final calculation without a FRY amount.
              value: !include docs/examples/get-calculation/request-final-without-fry.json

      responses:
        200:
          body:
            application/json:
              type: !include docs/schemas/get-calculation/success.json
              examples:
                example-1:
                  description: Example with all arrays populated.
                  value: !include docs/examples/get-calculation/success.json
                example-2:
                  description: Example with no notes or qualifying years.
                  value: !include docs/examples/get-calculation/success-empty-arrays.json

      (annotations.sandboxData): !include docs/testData.md
